#cloud-config
runcmd:
  - echo Cloud Config Start
  - sudo echo "server {"                                            >  /nginx.conf.tmp
  - sudo echo "    listen       80;"                                >> /nginx.conf.tmp
  - sudo echo "    server_name  localhost;"                         >> /nginx.conf.tmp
  - sudo echo "    error_page   500 502 503 504  /50x.html;"        >> /nginx.conf.tmp
  - sudo echo "    location = /50x.html {"                          >> /nginx.conf.tmp
  - sudo echo "        root   /usr/share/nginx/html;"               >> /nginx.conf.tmp
  - sudo echo "    }"                                               >> /nginx.conf.tmp
  - sudo echo "    location ~* \.(css|png)$ {"                      >> /nginx.conf.tmp
  - sudo echo "      root          /usr/share/nginx/html/static/;"  >> /nginx.conf.tmp
  - sudo echo "      expires       max;"                            >> /nginx.conf.tmp
  - sudo echo "      access_log    off;"                            >> /nginx.conf.tmp
  - sudo echo "    }"                                               >> /nginx.conf.tmp
  - sudo echo "    location / {"                                    >> /nginx.conf.tmp
  - sudo echo "      proxy_pass http://${host}:80/;"                >> /nginx.conf.tmp
  - sudo echo "    }"                                               >> /nginx.conf.tmp
  - sudo echo "}"                                                   >> /nginx.conf.tmp
  - sudo docker pull ${image}
  - until $(curl -sfI -o /dev/null http://${host}); do printf '.'; sleep 5; done
  - sudo docker run -d -p 80:80 -v /nginx.conf.tmp:/etc/nginx/conf.d/default.conf ${image}
  - echo Cloud Config Finish
